import { definePreset } from './registry.js';

/** `sparkle`: a small crisp glint — a tight core with two crossed fans. */
export const sparkle = definePreset({
  version: 1,
  color: '#FFFFFF',
  rotation: 0,
  seed: 4,
  shards: [
    {
      id: 'bloom',
      kind: 'blob',
      channel: 'body',
      strength: 0.25,
      size: 0.28,
      hardness: 0,
      falloff: 3,
      softness: 2,
    },
    {
      id: 'hotspot',
      kind: 'blob',
      channel: 'body',
      strength: 1,
      size: 0.08,
      hardness: 0.5,
      falloff: 2,
    },
    {
      id: 'spikes',
      kind: 'fan',
      channel: 'rays',
      strength: 1,
      size: 0.42,
      count: 6,
      width: 3,
      taper: 1,
      falloff: 2,
      softness: 1,
    },
    {
      id: 'glint',
      kind: 'fan',
      channel: 'glint',
      strength: 0.6,
      size: 0.26,
      count: 6,
      angle: 30,
      width: 2,
      taper: 1,
      falloff: 2,
      softness: 1,
    },
  ],
});
