import { definePreset } from './registry.js';

/** `sun`: a big soft sun with many faint, slightly jittered rays. */
export const sun = definePreset({
  version: 1,
  color: '#FFE9B8',
  rotation: 0,
  seed: 2,
  shards: [
    {
      id: 'bloom',
      kind: 'blob',
      channel: 'body',
      strength: 0.55,
      size: 1.15,
      hardness: 0,
      falloff: 2.6,
      softness: 5,
    },
    {
      id: 'hotspot',
      kind: 'blob',
      channel: 'body',
      strength: 1,
      size: 0.22,
      hardness: 0.3,
      falloff: 2,
    },
    {
      id: 'rays',
      kind: 'fan',
      channel: 'rays',
      strength: 0.45,
      size: 1,
      count: 32,
      variance: 0.7,
      jitter: 0.55,
      inner: 0.06,
      width: 2,
      taper: 1,
      falloff: 1.6,
      fadeIn: 0.05,
      softness: 1.5,
    },
    {
      id: 'ring',
      kind: 'halo',
      channel: 'rays',
      strength: 0.04,
      size: 0.8,
      width: 0.07,
      falloff: 2,
      softness: 2.5,
      variance: 0.4,
    },
  ],
});
